### PR TITLE
Feature/show idcode

### PR DESCRIPTION
**Pull request by 0ff**
This PR adds an output for every plausible IDCODE-Scan Result showing the IDCODE that was found.

This is the current output:
```
TDI: N/A
TDO: 17
TCK: 21
TMS: 22
TRST#: 0
-------------------------------
IDCODE scan complete.
```
You'd now have to type `d` and confirm the pins to see the (already determined, just now shown!) IDCODE.

With this PR, it will be like that:
```
TDI: N/A
TDO: 17
TCK: 21
TMS: 22
Device ID #1: 0111 1111111111111111 11111111111 1 (0x1F0F0F0F)
TRST#: 0 - Device ID #1: 1111 1111111111111111 11111111111 1 (0xFFFFFFFF)
-------------------------------
IDCODE scan complete.
```
So there's no need to run `d` anymore.

This is especially handy when you find multiple possible JTAG ports on the same connector.

Also, I included a `.gitattributes` file to mark `.spin`-files as *diffable*. The next PR should now hopefully display the source with a diff instead of saying `Binary file not shown.`

### CODE REVIEW

**Comment by 0ff** [comment]
It **should** just affect display on github/other git gui tools, but to be honest I've only ever used it once before (also for UTF-16 files). If you don't like it, I could remove the commit? Just thought it would be great to see the diff on github instead of having to pull/diff locally.

**Comment by joegrand** [comment]
Unfortunately, your modification for IDCODE won't work for targets with more than one device in the JTAG chain. Since IDCODE doesn't require TDI and we likely don't know it yet, we can't do a test to determine how many devices there are in the chain. So, IDCODE_Scan is just looking for the first device in the chain. That means you'll only ever retrieve the first IDCODE of the target, which would give incomplete information to the user. I had a similar feature in a very early release, but removed it for that reason. With the Get IDCODE command (IDCODE_Known), we are doing things a bit differently by entering the Shift_DR state and shifting a large number to see how many Device ID's we can find. Hence, multiple devices in the JTAG chain are detected and their Device ID's properly displayed.

**Comment by 0ff** [comment]
Okay I get that, but then maybe show it with that information? I've just added it for my convenience, as it really helped when I was getting many false-positives due to unrelated pins being tested. Just seeing  the first (and in my case: only) IDCODE would tell if these were the correct pins.

**Comment by joegrand** [comment]
Regarding .gitattributes, the diff attribute just showed the UTF-16 as UTF-8, so every other character was garbage. I'm going to err on the side of caution and not mess with any attribute settings, even though it's slightly annoying to diff locally.

**Comment by 0ff** [comment]
As for the `.gitattributes`: I've remove the commit, so this PR is only about IDCODE now. 

I don't have a screencapture handy now, but essentially the JTAGulator found a lot (like 20+) possible pinouts for TDO, TCK, TMS and especially TRST#. I guess there must be a clock on one of the connectors I tried, so I had to try `d` for every combination found, which was doable yet annoying. Then, looking over the source I saw that you've already inquired the IDCODE and I thought I'd just print it for every combination so the user wouldn't need to run the single-detect for every possible combination found.

**Comment by joegrand** [comment]
Were you able to determine the correct pinout using that method? I'm just trying to wrap my head around the benefit of having more information during the IDCODE_Scan command that could be incorrect and/or misleading. The typical process would be to use IDCODE_Scan as the quick test to see if there are any possibilities, then use BYPASS_Scan to verify (which lets you enter the pin numbers just detected with IDCODE_Scan). It still requires some manual intervention, especially if you have multiple results from IDCODE_Scan, but it's the most effective/reliable method. Sometimes, the target doesn't have a Device ID, in which case only BYPASS_Scan would work.

**Comment by joegrand** [comment]
OK, I managed to make some changes to IDCODE_Scan to get all Device IDs for the current pin permutation to be displayed with only a small increase in scanning time. I'll push the changes shortly for you to verify. I'd like to see how it responds with your target setup, especially since it reports lots of false-positives.

BTW, I'm working from a local repo and pulled your changes into there.

**Comment by joegrand** [comment]
Code has been pushed to the main GitHub repo. Please give it a try and let me know the results. Thanks!

**Pull request closed without merging**
