### PR TITLE
Convert UTF-16 SPIN sources to 7-bit ASCII

### PR DESCRIPTION
**Pull request by adamgreen**
I massaged the extended characters in these source files to be
'equivalent' 7-bit ASCII characters. It was these extended characters
which required them being saved as UTF-16 by the Propeller Tool. If
they were opened in PropellerIDE, they would be converted to UTF-8
which could then not be opened by Propeller Tool. Both tools can read
these simpler ASCII files.

The advantage of using ASCII instead of UTF-16 include:
* Local git diffs and on GitHub work as expected since UTF-16 was
  treated as binary by default. I tried using .gitattributes to
  workaround this issue but I ran into difficulties with round tripping
  the files in and out of git. An example of a GitHub diff after this
  change can be seen in the SWD support branch that I am currently
  working on: https://github.com/adamgreen/jtagulator/commit/b86adf1c4f36585e28a7adbcba8278988e3d28fc
* This ASCII format is supported by both the Propeller Tool and
  PropellerIDE.

The main disadvantage is:
* The smooth frames that used to be drawn around text and tables in the
  code now use chunkier ASCII equivalents like "+-----+"

This match statement from the Rust code I used to automatically massage
these files shows which Unicode code points I switched to which ASCII
'equivalents'.
```Rust
    match ch {
        '\u{2500}' => write!(&mut new_file, "-").unwrap(),
        '\u{2502}' => write!(&mut new_file, "|").unwrap(),
        '\u{251c}'| '\u{2524}' | '\u{2514}' | '\u{2534}' | '\u{253c}' |
        '\u{2518}' | '\u{252c}' | '\u{2510}' | '\u{250c}'
                   => write!(&mut new_file, "+").unwrap(),
        '\u{2022}' => write!(&mut new_file, "*").unwrap(),
        '\u{b1}'   => write!(&mut new_file, "+/-").unwrap(),
        _ => panic!("{}-{:X}", ch, ch as u32)
    }
```
The full sources are located at:
  https://github.com/adamgreen/spin2ascii

### CODE REVIEW

**Comment by joegrand** [comment]
Super helpful - thanks for doing that! Successfully merged. 👍

**Comment by adamgreen** [comment]
@joegrand Thanks for such a cool tool, making it open source, and taking the time to review/merge my PR. Much appreciated!

**Comment by joegrand** [comment]
Hey @adamgreen! I have some new files to add soon into the JTAGulator repo. I didn't grab your spin2ascii source (https://github.com/adamgreen/spin2ascii) back in the day, though should have. Do you still have that code available?

**Comment by adamgreen** [comment]
I thought if files with no special characters were saved in the Propeller Tool, it wouldn't save them as UTF-16. Is that not the case?

I have made the [spin2ascii project](https://github.com/adamgreen/spin2ascii) available again just incase.

**Comment by joegrand** [comment]
Thanks for the quick response! 

I'm not sure about files with no special characters - you're probably right. The stuff I'm adding is from an old branch, so it has the special character headers. I figured it would be easier to make all files consistent with the method that you used previously.

**Comment by adamgreen** [comment]
> The stuff I'm adding is from an old branch, so it has the special character headers. I figured it would be easier to make all files consistent with the method that you used previously.

Sounds like a good plan.

**Pull request merged**
