### PR TITLE
adding a CON-figurable delay for the TCK generated by the JTAGulator

### PR DESCRIPTION
**Pull request by BenGardiner**

### CODE REVIEW

**Comment by joegrand** [comment]
I think this would work best as a configurable value from the menu, which I can do later on after the merge. Is the maximum possible clock speed using this delay (23.25kHz) any slower than without the delay code in there at all? In other words, will merging this in affect the TCK speed for anyone not wanting to slow the clock down?

**Comment by BenGardiner** [comment]
Good point -- would be more useful as a runtime configurable option from
the menu.

I'm sure there is a slowdown introduced by this changeset since the
propeller waitcnt() needs a fixed additive constant to account for the
minimum time the interpreter takes to process the call. I can measure the
impact this week, an probably put a if == 0 test. This will also have an
impact but presumably less-so in the case of no delay requested.

**Comment by joegrand** [comment]
Cool - thanks. I'm not sure when I'll be able to make the change as a runtime option, so I just want to make sure that things will still work properly (at default speed) before merging this in.

**Comment by joegrand** [comment]
@BenGardiner: Now that v1.5 is released, I'm going to take your PR and integrate it into my local repo. That way, the github repo won't accidentally get broken as I make it a configurable menu option. I'm going to use a table look-up like with the baud rates, so there won't be any chance of someone setting an incorrect value. No need for you to run any tests - I'll have to do that on my side, anyway. I'm going to close this PR and we can discuss offline as needed!

**Comment by joegrand** [comment]
Integrated into [release 1.6](https://github.com/grandideastudio/jtagulator/releases/tag/1.6) as a menu-selectable value from 1 to 22 kHz.

**Pull request closed without merging**
